name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Get VLC dependency
      run: |
        Invoke-WebRequest -Uri "https://www.nuget.org/api/v2/package/VideoLAN.LibVLC.Windows/3.0.16" -OutFile "libvlc-3.0.16.zip"
        Expand-Archive -Path "libvlc-3.0.16.zip"

    - name: Build
      run: go build -v
      env:
        CGO_CFLAGS: "-Ilibvlc-3.0.16\\build\\x64\\include"
        CGO_LDFLAGS: "-Llibvlc-3.0.16\\build\\x64"

   # - name: Test
   #   run: go test -v
