name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Download dependencies
      shell: pwsh
      run: ./build.ps1 -DownloadOnly
    
    - name: Build
      shell: pwsh
      run: ./build.ps1

    - name: Test
      run: go test .\...
